### ISSUE TITLE
Can not delete comment

### ISSUE THREAD

**Issue by MeEgor** [jlobos/instagram-web-api#9] opened 2018-03-04 07:50 UTC
comment not deleting, when I use
```
let result = await client.deleteComment({ mediaId: media.graphql.shortcode_media.id, commentId: "17910681670083819" })
console.log(result)
```
response is `{ status: 'ok' }`, but comment is on it's place

When I try to delete not my comment response is `{"message":"You cannot delete this comment","status":"fail"}`, as expected

**Comment by timolins** [comment] 2018-03-19 20:08
I wasn't able to reproduce this problem on my end. But i think it's caused by the Instagram API itself, and can't be fixed by this module.

Closing this issue for now.

**Closed by timolins** 2018-03-19 20:08 UTC
